---
language: generic
install: docker pull lpenz/ghaction-cmake:v0.9
script: >-
  docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD"
  -e INPUT_PRESET="$preset"
  -e INPUT_DEPENDENCIES_DEBIAN="libx11-dev xvfb xauth xterm"
  lpenz/ghaction-cmake:v0.9
jobs:
  include:
    - name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD" lpenz/omnilint
    - name: clang-format-lint
      install: docker pull DoozyX/clang-format-lint-action@v0.5
      script: >-
        docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD"
        DoozyX/clang-format-lint-action@v0.5
    - env: [ preset=cppcheck ]
    - env: [ preset=iwyu ]
    - env: [ preset=clang-tidy ]
    - env: [ preset=install ]
    - env: [ preset=clang-sanitizer-address ]
    - env: [ preset=clang-sanitizer-memory ]
    - env: [ preset=clang-sanitizer-undefined ]
    - env: [ preset=clang-sanitizer-dataflow ]
    - env: [ preset=clang-sanitizer-safe-stack ]
    - env: [ preset=valgrind ]
    - env: [ preset=coverage ]
      after_success:
        - docker pull codecov/codecov-action@v0.1
        - >-
          docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD"
          codecov/codecov-action@v0.1
