---
language: c
script:
  - SRC_DIR=$PWD
  - mkdir ../build ../install
  - cd ../build
  - cmake -DCMAKE_INSTALL_PREFIX=../install "$SRC_DIR"
  - make VERBOSE=1
  - make install
jobs:
  include:
    - env: [ ACTION=omnilint ]
      language: generic
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
    - env: [ ACTION=build ]
      compiler: gcc
    - env: [ ACTION=build ]
      compiler: clang

